stages:
  eda:
    cmd: python eda/eda_sample.py --input-train-data-path ./data/train.csv --input-test-data-path ./data/train.csv --output-plots-path ./target/eda/plots
    deps:
      - ./data/train.csv
      - ./data/test.csv
    outs:
      - ./target/eda
  preprocessing:
    cmd: python preprocessing/preprocessing_sample.py --input-train-data-path ./data/train.csv --input-test-data-path ./data/train.csv --output-train-data-path target/preprocessing/train_preprocessed.csv --output-test-data-path target/preprocessing/test_preprocessed.csv
    deps:
      - ./data/train.csv
      - ./data/test.csv
    outs:
      - ./target/preprocessing/test_preprocessed.csv
      - ./target/preprocessing/train_preprocessed.csv
  modelling:
    cmd: python modelling/modelling_sample.py --input-train-data-path ./target/preprocessing/train_preprocessed.csv --input-test-data-path ./target/preprocessing/test_preprocessed.csv --output-model-path ./target/modelling/model.pkl --output-predictions-data-path ./target/predictions/predictions.csv
    deps:
      - ./target/preprocessing/test_preprocessed.csv
      - ./target/preprocessing/train_preprocessed.csv
    outs:
      - ./target/modelling/model.pkl
      - ./target/predictions/predictions.csv